export type Language = 'en' | 'de' | 'zh' | 'ko' | 'ja';

export const languages = [
  { code: 'en' as Language, name: 'English' },
  { code: 'de' as Language, name: 'Deutsch' },
  { code: 'zh' as Language, name: '中文' },
  { code: 'ko' as Language, name: '한국어' },
  { code: 'ja' as Language, name: '日本語' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'LoL Notify Clip',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.highlights': 'Highlights',
    'nav.about': 'About',
    'signin.welcome': 'Welcome to Gaming Coach',
    'signin.subtitle': 'Sign in to access your personalized coaching',
    'signin.title': 'Sign In',
    'signin.userId': 'User ID',
    'signin.password': 'Password',
    'signin.button': 'Sign In',
    'signup.title': 'Sign Up',
    'signup.email': 'Email',
    'signup.confirmPassword': 'Confirm Password',
    'signup.continueButton': 'Continue',
    'verify.title': 'Verify Email',
    'verify.code': 'Verification Code',
    'verify.button': 'Verify',
    'verify.resend': 'Resend Code',
  },
  de: {
    'app.title': 'LoL Benachrichtigung Clip',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Einstellungen',
    'nav.highlights': 'Highlights',
    'nav.about': 'Über',
    'signin.welcome': 'Willkommen beim Gaming Coach',
    'signin.subtitle': 'Melden Sie sich an',
    'signin.title': 'Anmelden',
    'signin.userId': 'Benutzer-ID',
    'signin.password': 'Passwort',
    'signin.button': 'Anmelden',
    'signup.title': 'Registrieren',
    'signup.email': 'E-Mail',
    'signup.confirmPassword': 'Passwort bestätigen',
    'signup.continueButton': 'Weiter',
    'verify.title': 'E-Mail verifizieren',
    'verify.code': 'Verifizierungscode',
    'verify.button': 'Verifizieren',
    'verify.resend': 'Code erneut senden',
  },
  zh: {
    'app.title': 'LoL 通知剪辑',
    'nav.dashboard': '仪表板',
    'nav.settings': '设置',
    'nav.highlights': '精彩集锦',
    'nav.about': '关于',
    'signin.welcome': '欢迎来到游戏教练',
    'signin.subtitle': '登录以访问您的个性化指导',
    'signin.title': '登录',
    'signin.userId': '用户ID',
    'signin.password': '密码',
    'signin.button': '登录',
    'signup.title': '注册',
    'signup.email': '电子邮件',
    'signup.confirmPassword': '确认密码',
    'signup.continueButton': '继续',
    'verify.title': '验证电子邮件',
    'verify.code': '验证码',
    'verify.button': '验证',
    'verify.resend': '重新发送代码',
  },
  ko: {
    'app.title': 'LoL 알림 클립',
    'nav.dashboard': '대시보드',
    'nav.settings': '설정',
    'nav.highlights': '하이라이트',
    'nav.about': '정보',
    'signin.welcome': '게임 코치에 오신 것을 환영합니다',
    'signin.subtitle': '로그인하세요',
    'signin.title': '로그인',
    'signin.userId': '사용자 ID',
    'signin.password': '비밀번호',
    'signin.button': '로그인',
    'signup.title': '가입',
    'signup.email': '이메일',
    'signup.confirmPassword': '비밀번호 확인',
    'signup.continueButton': '계속',
    'verify.title': '이메일 확인',
    'verify.code': '인증 코드',
    'verify.button': '확인',
    'verify.resend': '코드 재전송',
  },
  ja: {
    'app.title': 'LoL 通知クリップ',
    'nav.dashboard': 'ダッシュボード',
    'nav.settings': '設定',
    'nav.highlights': 'ハイライト',
    'nav.about': 'について',
    'signin.welcome': 'ゲーミングコーチへようこそ',
    'signin.subtitle': 'サインインしてください',
    'signin.title': 'サインイン',
    'signin.userId': 'ユーザーID',
    'signin.password': 'パスワード',
    'signin.button': 'サインイン',
    'signup.title': 'サインアップ',
    'signup.email': 'メールアドレス',
    'signup.confirmPassword': 'パスワードを確認',
    'signup.continueButton': '続ける',
    'verify.title': 'メール確認',
    'verify.code': '確認コード',
    'verify.button': '確認',
    'verify.resend': 'コードを再送信',
  },
};

export function translate(language: Language, key: string): string {
  return translations[language][key] || translations['en'][key] || key;
}
