
openapi: 3.0.3
info: { title: Rift Rewind API, version: 0.1.0 }
paths:
  /health: { get: { responses: { '200': { description: OK }}}}
  /summary/{puuid}:
    get:
      parameters: [{ in: path, name: puuid, required: true, schema: { type: string }}]
      responses: { '200': { description: Player summary JSON }}
  /ingest/{puuid}:
    post:
      parameters: [{ in: path, name: puuid, required: true, schema: { type: string }}]
      responses: { '202': { description: Ingest started }}
  /mirror/{matchId}:
    get:
      parameters: [{ in: path, name: matchId, required: true, schema: { type: string }}]
      responses: { '200': { description: Mirror summary }}
  /patch-mentor/{puuid}:
    get:
      parameters: [{ in: path, name: puuid, required: true, schema: { type: string }}]
      responses: { '200': { description: Patch mentor tips }}
  /share/{puuid}/{cardId}:
    get:
      parameters:
        - { in: path, name: puuid, required: true, schema: { type: string }}
        - { in: path, name: cardId, required: true, schema: { type: string }}
      responses: { '200': { description: PNG image bytes }}
